### PR TITLE
Port configs from Angelica/ArchaicFix

### PR DESCRIPTION
**Pull request by Caedis**
This will allow our mods to easily create config files as well as allow them to be editable in game from the Forge config menu.

Should we also move this to here or even HP?
https://github.com/GTNewHorizons/EnderCore/blob/master/src/main/java/com/enderio/core/client/gui/bettermodlist/EventHandlerGui.java

This allows the forge config gui to work in game.

### CODE REVIEW

**Comment by Glease** [comment]
1. lombok? if possible, at least make sure it doesn't got passed down  the dependency chain
2. where does this piece of code come from? I'd imagine it's not yours code, nor code of anyone inside GTNH org. proper credit need to be given somehow

**Comment by Caedis** [comment]
It all came from https://github.com/GTNewHorizons/Angelica/tree/master/src/main/java/com/gtnewhorizons/angelica/config so ask @mitchej123

**Comment by Caedis** [comment]
How would I make sure deps dont add it?

**Comment by Caedis** [comment]
Looks like the original source is AF, which is LGPL-3
https://github.com/embeddedt/ArchaicFix/tree/main/src/main/java/org/embeddedt/archaicfix/config

**Comment by bombcar** [comment]
> How would I make sure deps dont add it?

According to https://wiki.gtnewhorizons.com/wiki/Development#Dependency_types you have the right one, it shouldn't be pulled into further things downstream.

**Comment by mitchej123** [comment]
Should probably add something to Credits indicating where it came from and the license.  I didn't realize it came to AF via FPL or I would have included that in Angelica's credits.

**Comment by mitchej123** [comment]
Yah, talked to FP - he's fine with it going here, but let's put a mention in the credits/readme giving them credit

**Comment by Caedis** [comment]
I actually had that ready to commit/push for awhile

**Review by mitchej123 — APPROVED** [review]

**Pull request merged**
